server:
  port: 8001

spring:
  profiles:
    active: dev
  #MongoDB连接配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
  #数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/guiguxiaozhi?useUnicode:true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#开启MybatisPlus日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

langchain4j:
  #openai模型配置
  open-ai:
    chat-model:
      #base-url: http://langchain4j.dev/demo/openai/v1
      base-url: https://api.deepseek.com
      api-key: ${OPENAI_API_KEY}
      model-name: deepseek-chat
      #日志开关
      log-requests: true
      log-responses: true
  #本地ollama模型配置
  ollama:
    chat-model:
      base-url: http://localhost:11434
      log-requests: true
      log-responses: true
      model-name: deepseek-r1:1.5b
  #阿里云百炼模型配置
  community:
    dashscope:
      chat-model:
        api-key: ${OPENAI_API_KEY}
        model-name: qwen-max

logging:
  level:
    root: DEBUG
